"""Initial migration with all models

Revision ID: 9862a2ed6446
Revises: 
Create Date: 2026-05-02 13:41:51.775797

"""
from alembic import op
import sqlalchemy as sa


revision = '9862a2ed6446'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
